sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - make
    - automake
    - gcc
    - build-essential
    - g++
    - cpp
    - libc6-dev
    - man-db
    - autoconf
    - pkg-config
    - libtool
    - git
    - pigz

language: rust
cache:
  cargo: true
rust:
- stable
- nightly
env:
  global:
  - RUST_BACKTRACE=full
  - PATH=$HOME/.local/bin:$PATH
  - LD_LIBRARY_PATH=$HOME/lib
  - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
matrix:
  allow_failures:
  - rust: nightly
os:
- linux

before_script: # copied from erickt/rust-zmq
- |
  set -e
  git clone --depth 1 -b stable https://github.com/jedisct1/libsodium.git
  cd libsodium
  ./autogen.sh
  ./configure --prefix=$HOME
  make
  make install
  cd ..
  wget https://github.com/zeromq/zeromq4-1/archive/v4.1.6.tar.gz
  tar zxf v4.1.6.tar.gz
  cd zeromq4-1-4.1.6
  ./autogen.sh
  ./configure --prefix=$HOME --with-libsodium
  make
  make install
  cd ..

script:
- cargo test
