[package]
name = "apart-core"
version = "0.2.3"
authors = ["Alex Butler <alexheretic@gmail.com>"]

[dependencies]
zmq = "0.8.2"
yaml-rust = "0.3"
log = "0.3"
wait-timeout = "0.1"
env_logger = "0.4"
regex = "0.2"
chrono = "0.4"
json = "0.11"
uuid = { version = "0.5", features = ["v4"] }

[dev-dependencies]
flate2 = "0.2"
