[package]
name = "apart-core"
version = "0.3.5"
authors = ["Alex Butler <alexheretic@gmail.com>"]

[dependencies]
zmq = "0.8.2"
yaml-rust = "0.4"
log = "0.4"
env_logger = "0.5"
regex = "1"
chrono = "0.4"
json = "0.11"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
wait-timeout = "0.1"
flate2 = "1"
